name: Build Windows EXE

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync

      - name: Build EXE
        run: |
          run: uv run pyinstaller --onefile --windowed --collect-all nicegui --name Notes app/main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Notes
          path: dist/Notes.exe